language: java
jdk:
  - openjdk8
  
addons:
  sonarcloud:
    organization: flaviamagnoni-1
    token:
      secure:435947611031868d73d01652ec4d744596a99b23
script: 
- ant build
- sonar-scanner