language: java
jdk:
  - openjdk8
  
addons:
  sonarcloud:
    organization: "flaviamagnoni-1"
    token:
      secure: 375dc2a15922f50cf0de5e63e955e7118b8f337d
script: 
- ant build
- sonar-scanner